/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.developed.jticket.forms;

import br.com.developed.jticket.config.ConfiguracaoHandler;
import br.com.developed.jticket.constraints.TipoPreco;
import br.com.developed.jticket.entities.Categoria;
import br.com.developed.jticket.entities.Departamento;
import br.com.developed.jticket.entities.Filial;
import br.com.developed.jticket.entities.Fornecedor;
import br.com.developed.jticket.entities.Produto;
import br.com.developed.jticket.entities.Regiao;
import br.com.developed.jticket.entities.Secao;
import br.com.developed.jticket.entities.SubCategoria;
import br.com.developed.jticket.models.FiltroProduto;
import br.com.developed.jticket.services.EtiquetaEletronicaService;
import br.com.developed.jticket.services.FilialService;
import br.com.developed.jticket.services.ParametroValorService;
import br.com.developed.jticket.services.ProdutoService;
import java.io.IOException;
import java.util.Date;
import java.util.List;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationContext;

/**
 *
 * @author carlos
 */
@Slf4j
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal(ApplicationContext ctx) {
        this.ctx = ctx;
        initComponents();
        configuraLaf();
        verificaTipoPreço();
        jTextAreaLogDebug.setEnabled(false);
        jTextFieldFilial.setEnabled(false);
        jButtonPesquisaDepartamento.setEnabled(false);
        jTextFieldDepartamento.setEnabled(false);
        jButtonPesquisaSecao.setEnabled(false);
        jTextFieldSecao.setEnabled(false);        
        jButtonPesquisaCategoria.setEnabled(false);
        jTextFieldCategoria.setEnabled(false);
        jButtonPesquisaSubCategoria.setEnabled(false);
        jTextFieldSubCategoria.setEnabled(false);
        jButtonPesquisaProduto.setEnabled(false);
        jTextFieldProduto.setEnabled(false);        
        jButtonPesquisaFornecedor.setEnabled(false);
        jTextFieldFornecedor.setEnabled(false);
        jCheckBoxEstoquePositivo.setEnabled(false);
        jCheckBoxProdutoAtivo.setEnabled(false);
        jTextFieldArea.setEnabled(false);
        jButtonProcessar.setEnabled(false);
        jButtonPesquisaProdPrincipal.setEnabled(false);
        jTextFieldProdPrincipal.setEnabled(false);
                
    }
    
    private void configuraLaf() {
        
        try {
            log.info("LAF -> " + ConfiguracaoHandler.getInstance().getLaf());
            if(ConfiguracaoHandler.getInstance().getLaf() != null) {
                UIManager.setLookAndFeel(ConfiguracaoHandler.getInstance().getLaf());
            } else {
                UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
            }
            SwingUtilities.updateComponentTreeUI(this);
        } catch (IOException e) {
            log.error("Ocorreu um erro ao ler o arquivo de configuração.", e);
        } catch (ClassNotFoundException e) {
            log.error("Classe do LAF não localizado.", e);
        } catch (InstantiationException e) {
            log.error("Ocorreu um erro ao instanciar a classe", e);
        } catch (IllegalAccessException e) {
            log.error("Erro ao carregar o LAF", e);
        } catch (UnsupportedLookAndFeelException e) {
            log.error("Erro ao carregar o LAF", e);
        }
    }
    
    private void verificaTipoPreço() {
        ParametroValorService service = ctx.getBean(ParametroValorService.class);
        TipoPreco tipoPreco = service.verificaTipoPreco();
        if(tipoPreco.equals(TipoPreco.PRODUTO)) {
            jLabel11.setText("Winthor configurado como venda por produto (Prec. rot. 201)");
        } else {
            jLabel11.setText("Winthor configurado como venda por embalagem (Prec. rot. 2017)");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateLabelFormatter1 = new org.jdatepicker.DateLabelFormatter();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCheckBoxProdutoAtivo = new javax.swing.JCheckBox();
        jCheckBoxEstoquePositivo = new javax.swing.JCheckBox();
        jButtonPesquisaProdPrincipal = new javax.swing.JButton();
        jTextFieldProdPrincipal = new javax.swing.JTextField();
        jButtonPesquisaFornecedor = new javax.swing.JButton();
        jTextFieldFornecedor = new javax.swing.JTextField();
        jButtonPesquisaProduto = new javax.swing.JButton();
        jTextFieldProduto = new javax.swing.JTextField();
        jButtonPesquisaSubCategoria = new javax.swing.JButton();
        jTextFieldSubCategoria = new javax.swing.JTextField();
        jButtonPesquisaCategoria = new javax.swing.JButton();
        jTextFieldCategoria = new javax.swing.JTextField();
        jButtonPesquisaSecao = new javax.swing.JButton();
        jTextFieldSecao = new javax.swing.JTextField();
        jButtonPesquisaDepartamento = new javax.swing.JButton();
        jTextFieldDepartamento = new javax.swing.JTextField();
        jButtonPesquisaFilial = new javax.swing.JButton();
        jTextFieldArea = new javax.swing.JTextField();
        jTextFieldFilial = new javax.swing.JTextField();
        jButtonProcessar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaLogDebug = new javax.swing.JTextArea();
        jButtonPesquisaRegiao = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jCheckBoxFiltroDataPrecoAlterado = new javax.swing.JCheckBox();
        dateChooserCombo3 = new datechooser.beans.DateChooserCombo();
        dateChooserCombo4 = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Developed - Ticket - Integrador Toledo.");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Filial");

        jLabel2.setText("Região");

        jLabel3.setText("Departamento");

        jLabel4.setText("Seção");

        jLabel5.setText("Categoria");

        jLabel6.setText("Sub-Categoria");

        jLabel7.setText("Produto");

        jLabel8.setText("Fornecedor");

        jLabel9.setText("Prod. Principal");

        jCheckBoxProdutoAtivo.setText("Considerar apenas produtos ativos (não excluídos)");

        jCheckBoxEstoquePositivo.setText("Considerar somente produtos com estoque maior que zero");
        jCheckBoxEstoquePositivo.setToolTipText("");

        jButtonPesquisaProdPrincipal.setText("...");
        jButtonPesquisaProdPrincipal.setToolTipText("");

        jButtonPesquisaFornecedor.setText("...");
        jButtonPesquisaFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaFornecedorActionPerformed(evt);
            }
        });

        jButtonPesquisaProduto.setText("...");
        jButtonPesquisaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaProdutoActionPerformed(evt);
            }
        });

        jButtonPesquisaSubCategoria.setText("...");
        jButtonPesquisaSubCategoria.setToolTipText("");
        jButtonPesquisaSubCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaSubCategoriaActionPerformed(evt);
            }
        });

        jButtonPesquisaCategoria.setText("...");
        jButtonPesquisaCategoria.setToolTipText("");
        jButtonPesquisaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaCategoriaActionPerformed(evt);
            }
        });

        jButtonPesquisaSecao.setText("...");
        jButtonPesquisaSecao.setToolTipText("");
        jButtonPesquisaSecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaSecaoActionPerformed(evt);
            }
        });

        jButtonPesquisaDepartamento.setText("...");
        jButtonPesquisaDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaDepartamentoActionPerformed(evt);
            }
        });

        jButtonPesquisaFilial.setText("...");
        jButtonPesquisaFilial.setToolTipText("");
        jButtonPesquisaFilial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaFilialActionPerformed(evt);
            }
        });

        jTextFieldFilial.setToolTipText("");

        jButtonProcessar.setMnemonic('P');
        jButtonProcessar.setText("Processar");
        jButtonProcessar.setToolTipText("Executa o processamento");
        jButtonProcessar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProcessarActionPerformed(evt);
            }
        });

        jButtonLimpar.setMnemonic('L');
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.setToolTipText("Limpa os filtros para um novo processamento");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSair.setMnemonic('S');
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTextAreaLogDebug.setColumns(20);
        jTextAreaLogDebug.setRows(5);
        jScrollPane1.setViewportView(jTextAreaLogDebug);

        jButtonPesquisaRegiao.setText("...");
        jButtonPesquisaRegiao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisaRegiaoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("jLabel11");

        jCheckBoxFiltroDataPrecoAlterado.setText("Filtrar produtos com preços alterados no período");
        jCheckBoxFiltroDataPrecoAlterado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxFiltroDataPrecoAlteradoActionPerformed(evt);
            }
        });

        dateChooserCombo3.setEnabled(false);
        dateChooserCombo3.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        dateChooserCombo4.setEnabled(false);
        dateChooserCombo4.setBehavior(datechooser.model.multiple.MultyModelBehavior.SELECT_SINGLE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBoxEstoquePositivo)
                            .addComponent(jCheckBoxProdutoAtivo)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButtonPesquisaFilial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaDepartamento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaSecao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaSubCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaProduto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaProdPrincipal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButtonPesquisaRegiao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldArea)
                                            .addComponent(jTextFieldProdPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE)
                                            .addComponent(jTextFieldFornecedor)
                                            .addComponent(jTextFieldProduto)
                                            .addComponent(jTextFieldSubCategoria)
                                            .addComponent(jTextFieldCategoria)
                                            .addComponent(jTextFieldSecao)
                                            .addComponent(jTextFieldDepartamento)
                                            .addComponent(jTextFieldFilial)))
                                    .addComponent(jCheckBoxFiltroDataPrecoAlterado)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(dateChooserCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateChooserCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButtonProcessar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jButtonPesquisaFilial)
                            .addComponent(jTextFieldFilial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPesquisaRegiao))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jButtonPesquisaDepartamento)
                            .addComponent(jTextFieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jButtonPesquisaSecao)
                            .addComponent(jTextFieldSecao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jButtonPesquisaCategoria)
                            .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jButtonPesquisaSubCategoria)
                            .addComponent(jTextFieldSubCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jButtonPesquisaProduto)
                            .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jButtonPesquisaFornecedor)
                            .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPesquisaProdPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jTextFieldProdPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBoxFiltroDataPrecoAlterado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dateChooserCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(dateChooserCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxProdutoAtivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxEstoquePositivo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonProcessar)
                            .addComponent(jButtonLimpar))
                        .addGap(30, 30, 30))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSair)
                    .addComponent(jLabel11))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisaFilialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaFilialActionPerformed
        
        FormSelecaoFilial f = new FormSelecaoFilial(this, true, ctx);
        f.setVisible(true);
        filial = f.getFilialSel();
        
        if(filial != null) {
            jTextAreaLogDebug.setEnabled(false);        
            jButtonPesquisaDepartamento.setEnabled(true);        
            jButtonPesquisaSecao.setEnabled(true);                        
            jButtonPesquisaCategoria.setEnabled(true);
            jButtonPesquisaSubCategoria.setEnabled(true);
            jButtonPesquisaProduto.setEnabled(true);                      
            jButtonPesquisaFornecedor.setEnabled(true);
            jButtonPesquisaProdPrincipal.setEnabled(true);
            jCheckBoxEstoquePositivo.setEnabled(true);
            jCheckBoxProdutoAtivo.setEnabled(true);
            jTextFieldArea.setEnabled(false);
            jButtonProcessar.setEnabled(true);
            
            jTextFieldFilial.setText(String.format("%s - %s", filial.getCodigo(), filial.getRazaosocial()));
        }
        f.dispose();
            
    }//GEN-LAST:event_jButtonPesquisaFilialActionPerformed

    private void jButtonPesquisaSecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaSecaoActionPerformed

        
        FormSelecaoSecao f = new FormSelecaoSecao(this, true, (departamentos == null ? null : departamentos.get(0)), ctx);
        f.setVisible(true);
        secoes = f.getSecoesSel();
        f.dispose();
        if(secoes != null) {
            
            if(secoes.size() == 1) {
                jTextFieldSecao.setText(String.format("%d - %s", secoes.get(0).getCodsec(), secoes.get(0).getDescricao()));
            } else {
                jTextFieldSecao.setText("MÚLTIPLOS");
            }
            
            jTextAreaLogDebug.setEnabled(false);
            jTextFieldFilial.setEnabled(false);
            jButtonPesquisaFilial.setEnabled(false);
            jButtonPesquisaDepartamento.setEnabled(false);        
            jButtonPesquisaSecao.setEnabled(true);
            jButtonPesquisaCategoria.setEnabled(true);
            jButtonPesquisaSubCategoria.setEnabled(true);                        
            jButtonPesquisaProduto.setEnabled(true);                      
            jButtonPesquisaFornecedor.setEnabled(true);
            jButtonPesquisaProdPrincipal.setEnabled(true);
            jCheckBoxEstoquePositivo.setEnabled(true);
            jCheckBoxProdutoAtivo.setEnabled(true);
            jTextFieldArea.setEnabled(false);
            jButtonProcessar.setEnabled(true);
        }
            
    }//GEN-LAST:event_jButtonPesquisaSecaoActionPerformed

    private void jButtonPesquisaDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaDepartamentoActionPerformed
        
        FormSelecaoDepartamento f = new FormSelecaoDepartamento(this, true, ctx);
        f.setVisible(true);
        departamentos = f.getDepartamentosSel();
        
        if(departamentos != null) {
            
            if(departamentos.size() == 1) {
                jTextFieldDepartamento.setText(
                        String.format("%d - %s", departamentos.get(0).getCodepto(), 
                                departamentos.get(0).getDescricao()));
            } else {
                jTextFieldDepartamento.setText("MÚLTIPLOS");
            }
            
            jTextAreaLogDebug.setEnabled(false);
            jTextFieldFilial.setEnabled(false);
            jButtonPesquisaFilial.setEnabled(false);
            jButtonPesquisaDepartamento.setEnabled(true);        
            jButtonPesquisaSecao.setEnabled(true);
            jButtonPesquisaCategoria.setEnabled(true);
            jButtonPesquisaSubCategoria.setEnabled(true);                       
            jButtonPesquisaProduto.setEnabled(true);                        
            jButtonPesquisaFornecedor.setEnabled(true);
            jButtonPesquisaProdPrincipal.setEnabled(true);
            jCheckBoxEstoquePositivo.setEnabled(true);
            jCheckBoxProdutoAtivo.setEnabled(true);
            jTextFieldArea.setEnabled(false);
            jButtonProcessar.setEnabled(true);
        }
        
            
    }//GEN-LAST:event_jButtonPesquisaDepartamentoActionPerformed

    private void jButtonPesquisaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaCategoriaActionPerformed
        
        FormSelecaoCategoria f = new FormSelecaoCategoria(this, true, ctx, secoes);
        f.setVisible(true);
        categorias = f.getCategoriasSel();
        f.dispose();
        
        if(categorias != null) {
            
            if(categorias.size() == 1) {
                jTextFieldCategoria.setText(
                        String.format("%d - %s", categorias.get(0).getCodcategoria(), 
                                categorias.get(0).getCategoria()));
            } else {
                jTextFieldCategoria.setText("MÚLTIPLOS");
            }
            
            jTextAreaLogDebug.setEnabled(false);
            jTextFieldFilial.setEnabled(false);
            jButtonPesquisaFilial.setEnabled(false);
            jButtonPesquisaDepartamento.setEnabled(false);        
            jButtonPesquisaSecao.setEnabled(false);
            jButtonPesquisaCategoria.setEnabled(true);
            jButtonPesquisaSubCategoria.setEnabled(true);                        
            jButtonPesquisaProduto.setEnabled(true);                        
            jButtonPesquisaFornecedor.setEnabled(true);
            jButtonPesquisaProdPrincipal.setEnabled(true);
            jCheckBoxEstoquePositivo.setEnabled(true);
            jCheckBoxProdutoAtivo.setEnabled(true);
            jTextFieldArea.setEnabled(false);
            jButtonProcessar.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButtonPesquisaCategoriaActionPerformed

    private void jButtonPesquisaSubCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaSubCategoriaActionPerformed
        
        FormSelecaoSubCategoria f = new FormSelecaoSubCategoria(this, true, ctx, categorias);
        f.setVisible(true);
        subCategorias = f.getSubCategoriasSel();
        f.dispose();
        
        if(subCategorias != null) {
            
            if(subCategorias.size() == 1) {
                jTextFieldSubCategoria.setText(
                        String.format("%d - %s", subCategorias.get(0).getCodsubcategoria(), 
                                subCategorias.get(0).getCodsubcategoria()));
            } else {
                jTextFieldSubCategoria.setText("MÚLTIPLOS");
            }
            
        }
        
        jTextAreaLogDebug.setEnabled(false);
        jTextFieldFilial.setEnabled(false);
        jButtonPesquisaFilial.setEnabled(false);
        jButtonPesquisaDepartamento.setEnabled(false);        
        jButtonPesquisaSecao.setEnabled(false);                        
        jButtonPesquisaCategoria.setEnabled(false);
        jButtonPesquisaSubCategoria.setEnabled(true);
        jButtonPesquisaProduto.setEnabled(true);                      
        jButtonPesquisaFornecedor.setEnabled(true);
        jButtonPesquisaProdPrincipal.setEnabled(true);
        jCheckBoxEstoquePositivo.setEnabled(true);
        jCheckBoxProdutoAtivo.setEnabled(true);
        jTextFieldArea.setEnabled(false);
        jButtonProcessar.setEnabled(true);
    }//GEN-LAST:event_jButtonPesquisaSubCategoriaActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        jTextFieldFilial.setText("");
        jTextFieldDepartamento.setText("");
        jTextFieldSecao.setText("");
        jTextFieldCategoria.setText("");
        jTextFieldSubCategoria.setText("");
        jTextFieldProduto.setText("");        
        jTextFieldFornecedor.setText("");
        jTextFieldProdPrincipal.setText("");
        jTextAreaLogDebug.setText("");        
        jCheckBoxEstoquePositivo.setSelected(false);
        jCheckBoxProdutoAtivo.setSelected(false);
        

        jButtonPesquisaFilial.setEnabled(true);        
        jButtonPesquisaDepartamento.setEnabled(false);       
        jButtonPesquisaSecao.setEnabled(false);        
        jButtonPesquisaCategoria.setEnabled(false);        
        jButtonPesquisaSubCategoria.setEnabled(false);                
        jButtonPesquisaProduto.setEnabled(false);                       
        jButtonPesquisaFornecedor.setEnabled(false);
        jButtonPesquisaProdPrincipal.setEnabled(false);
        jCheckBoxEstoquePositivo.setEnabled(false);
        jCheckBoxProdutoAtivo.setEnabled(false);        
        jButtonProcessar.setEnabled(false);
        
        resetaObjetosCarregados();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonPesquisaRegiaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaRegiaoActionPerformed
        FormSelecaoRegiao f = new FormSelecaoRegiao(this, true, ctx);
        f.setVisible(true);
        regiao = f.getRegiaoSel();
        f.dispose();
        if(regiao != null) {
            jTextFieldArea.setText(String.format("%d - %s", regiao.getNumregiao(), regiao.getRegiao()));
        }
    }//GEN-LAST:event_jButtonPesquisaRegiaoActionPerformed

    private void jButtonPesquisaFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaFornecedorActionPerformed
        FormSelecaoFornecedor f = new FormSelecaoFornecedor(this, true, ctx);
        f.setVisible(true);
        fornecedor = f.getFornecedorSel();
        f.dispose();
        if(fornecedor != null) {
            jTextFieldFornecedor.setText(String.format("%d - %s", fornecedor.getCodfornec(), fornecedor.getFornecedor()));
        }
    }//GEN-LAST:event_jButtonPesquisaFornecedorActionPerformed

    private void jButtonPesquisaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisaProdutoActionPerformed
        FormSelecaoProduto f = new FormSelecaoProduto(this, true, ctx);
        f.setVisible(true);
        produtos = f.getProdutosSel();
        f.dispose();
        if(produtos != null) {
            if(produtos.size() == 1) {
                jTextFieldProduto.setText(String.format("%d - %s", produtos.get(0).getCodprod(),
                        produtos.get(0).getDescricao()));
            } else {
                jTextFieldProduto.setText("MÚLTIPLOS");
            }
        }
        
    }//GEN-LAST:event_jButtonPesquisaProdutoActionPerformed

    private void jButtonProcessarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProcessarActionPerformed
        EtiquetaEletronicaService eService = ctx.getBean(EtiquetaEletronicaService.class);
        if(jCheckBoxFiltroDataPrecoAlterado.isSelected()) {
            eService = ctx.getBean(EtiquetaEletronicaService.class);
        
            eService.carregaCodProdutosComAlteracaoDePrecoPeriodo(filial, regiao, 
                new Date(dateChooserCombo3.getCurrent().getTimeInMillis()), new Date(dateChooserCombo4.getCurrent().getTimeInMillis()))
                .forEach(p -> System.out.println(p));
        } else {
            
            FiltroProduto filtro = FiltroProduto.builder()
                .categorias(categorias)
                .departamentos(departamentos)
                .fornecedor(fornecedor)
                .produtos(produtos)
                .secoes(secoes)
                .subcategorias(subCategorias)
                .build();
            
                ProdutoService produtoService = ctx.getBean(ProdutoService.class);
                produtos = produtoService.carregaProdutos(filtro);
                eService.geraEtiquetasEletronicas(filial, regiao, produtos);
        }
        
    }//GEN-LAST:event_jButtonProcessarActionPerformed

    private void jCheckBoxFiltroDataPrecoAlteradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxFiltroDataPrecoAlteradoActionPerformed
        dateChooserCombo3.setEnabled(jCheckBoxFiltroDataPrecoAlterado.isSelected());
        dateChooserCombo4.setEnabled(jCheckBoxFiltroDataPrecoAlterado.isSelected());
    }//GEN-LAST:event_jCheckBoxFiltroDataPrecoAlteradoActionPerformed

    private void resetaObjetosCarregados() {
        filial = null;
        departamentos = null;
        secoes = null;
        categorias = null;
        subCategorias = null;
        fornecedor = null;
        regiao = null;
        produtos = null;
    }
    
    private Filial filial;
    private List<Departamento> departamentos;
    private List<Secao> secoes;
    private List<Categoria> categorias;
    private List<SubCategoria> subCategorias;
    private Fornecedor fornecedor;
    private Regiao regiao;
    private List<Produto> produtos;
    
    private FilialService filialService;
    private final ApplicationContext ctx;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private datechooser.beans.DateChooserCombo dateChooserCombo3;
    private datechooser.beans.DateChooserCombo dateChooserCombo4;
    private org.jdatepicker.DateLabelFormatter dateLabelFormatter1;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisaCategoria;
    private javax.swing.JButton jButtonPesquisaDepartamento;
    private javax.swing.JButton jButtonPesquisaFilial;
    private javax.swing.JButton jButtonPesquisaFornecedor;
    private javax.swing.JButton jButtonPesquisaProdPrincipal;
    private javax.swing.JButton jButtonPesquisaProduto;
    private javax.swing.JButton jButtonPesquisaRegiao;
    private javax.swing.JButton jButtonPesquisaSecao;
    private javax.swing.JButton jButtonPesquisaSubCategoria;
    private javax.swing.JButton jButtonProcessar;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JCheckBox jCheckBoxEstoquePositivo;
    private javax.swing.JCheckBox jCheckBoxFiltroDataPrecoAlterado;
    private javax.swing.JCheckBox jCheckBoxProdutoAtivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaLogDebug;
    private javax.swing.JTextField jTextFieldArea;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldDepartamento;
    private javax.swing.JTextField jTextFieldFilial;
    private javax.swing.JTextField jTextFieldFornecedor;
    private javax.swing.JTextField jTextFieldProdPrincipal;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldSecao;
    private javax.swing.JTextField jTextFieldSubCategoria;
    // End of variables declaration//GEN-END:variables
}
